# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0648e2dced613cc0ee0b65ea8992b70d1c62bd908df461a898078fed46943bab8d4fe4214bf2b8939c984a9004b7ea68b34179f6d5e53ac1dfaf37e428c29aa0

test:
  secret_key_base: 28f343fcf340df1c704d698ba37a897e237e6cc716077dae521739d7f60e9a880a3ced68af60214c2be3eb8da36a3e508dbf81f72d77a5c536231fae6d80d819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
